spring.application.name=SpringBoot-OnlineShop

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# 注意看 URL 的變化，參數全部用分號 ; 隔開
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=OnlineShop;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Password123
