CREATE TABLE IF NOT EXISTS Product
(
    product_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name       VARCHAR(128) NOT NULL,
    category           VARCHAR(32)   NOT NULL,
    image_url          VARCHAR(256)  not null,
    price              INT           NOT NULL,
    stock              INT           NOT NULL,
    description        VARCHAR(1024),
    created            TIMESTAMP     NOT NULL,
    last_modified_date TIMESTAMP     NOT NULL
);